name: main
on: [push, pull_request]
jobs:
  build-windows:
    name: windows - nodejs ${{ matrix.node }}
    runs-on: windows-latest
    strategy:
      matrix:
        node:
          - 18
          - 16
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
          token: ${{ secrets.NPM_TOKEN }}
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          update: true
          install: |
            git
            mingw-w64-x86_64-gobject-introspection
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-cairo
            mingw-w64-x86_64-gstreamer
            mingw-w64-x86_64-gst-plugins-good
            mingw-w64-x86_64-gst-plugins-bad
            mingw-w64-x86_64-libsoup

      - name: Install & Build
        run: |
          ./windows/mingw_include_extra.sh
          export MINGW_WINDOWS_PATH=$(./windows/mingw_windows_path.sh)
          npm config set msvs_version 2022
          npm install --build-from-source

      # - name: Run tests
      #   run: |
      #     npx mocha                                 \
      #               --skip=callback                 \
      #               --skip=signal__non-introspected \
      #               tests/__run__.js
      
      - name: Publish binaries
        run: ./windows/publish.sh
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

